2021-04-28 17:38:36.167870: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-04-28 17:38:36.167931: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO:tensorflow:Starting running in train mode...
I0428 17:38:38.116253 140179189049152 run_summarization.py:440] Starting running in train mode...
/home/anshul/lbp_venv/lib/python3.8/site-packages/spacy/util.py:275: UserWarning: [W031] Model 'en_core_web_sm' (2.2.0) requires spaCy v2.2 and is incompatible with the current spaCy version (2.3.5). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
max_size of vocab was specified as 20000; we now have 20000 words. Stopping reading.
Finished constructing vocabulary of 20000 total words. Last word added: richie
Traceback (most recent call last):
  File "run_summarization.py", line 653, in <module>
    tf.app.run()
  File "/home/anshul/lbp_venv/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/anshul/lbp_venv/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/anshul/lbp_venv/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_summarization.py", line 488, in main
    sc_batcher = Sc_GenBatcher(vocab, hps_sc_generator)
  File "/home/anshul/Downloads/LAB BASED PROJECT/Skeleton-Based-Generation-Model/sc_batch.py", line 249, in __init__
    self.train_queue = self.fill_example_queue("data/trainfeature02.json")
  File "/home/anshul/Downloads/LAB BASED PROJECT/Skeleton-Based-Generation-Model/sc_batch.py", line 472, in fill_example_queue
    example = Sc_Example(text, label, pos_tagging, compression, dependency, self._vocab, self._hps)
  File "/home/anshul/Downloads/LAB BASED PROJECT/Skeleton-Based-Generation-Model/sc_batch.py", line 44, in __init__
    if len(text_sen_words) > hps.sc_max_enc_seq_len:
TypeError: '>' not supported between instances of 'int' and 'Flag'
